version: '3.6'

services:
  db_example:
    image: postgres:13.2-alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_DB: $TYPEORM_DATABASE
      POSTGRES_HOST: $TYPEORM_HOST
    networks:
      - db_example
    ports:
      - 5499:5432
    expose:
      - 5499
    volumes:
      - example_postgres:/var/lib/postgresql/data

volumes:
  example_postgres:

networks:
  db_example:
    driver: bridge
